
name: verify-docs-quality
on:
  push

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  vale:
    name: Run Vale
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get all changed files and use a comma separator in the output
        id: changed-files
        uses: tj-actions/changed-files@v34
        with:
          separator: ","

      - uses: errata-ai/vale-action@reviewdog
        id: vale
        with:
          debug: true
          fail_on_error: true
          reporter: github-check
          files: '${{ steps.changed-files.outputs.all_changed_files }}'
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
