
name: verify-docs-quality
on:
  push

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  vale:
    name: Run Vale
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run changed-files
        id: changed-files
        uses: tj-actions/changed-files@v34

      - name: Run changed-files
        id: vale
        uses: errata-ai/vale-action@reviewdog
        with:
          debug: true
          fail_on_error: true
          reporter: github-check
          filter_mode: nofilter
          # using '--output=/lib/rdjsonl.tmpl,README.md,.github/workflows/docs.yml'.
          files: '${{ toJSON(steps.changed-files.outputs.all_changed_files) }}'
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
