
name: verify-docs-quality
on:
  pull_request

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  vale:
    name: Run Vale
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false

      - uses: errata-ai/vale-action@reviewdog
        id: vale
        with:
          fail_on_error: true
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
