
name: verify-docs-quality
on:
  push

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  vale:
    name: Run Vale
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run changed-files with json output
        id: changed-files
        uses: tj-actions/changed-files@v34
        with:
          json: true

      - uses: errata-ai/vale-action@reviewdog
        with:
          debug: true
          fail_on_error: true
          reporter: github-check
          filter_mode: nofilter
          files: '[".github/workflows/docs.yml"]'
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
